app:
    build: .
    environment:
        REALM: prod
        REDIS_URL: "//redis:6379"
    links:
        - redis
    ports:
        - "8000:8000"
    command: gunicorn -b 0.0.0.0:8000 --worker-class gevent --workers 2 --max-requests 1000 requestbin:app

redis:
    image: redis
